name: zkalphaflow
region: nyc

services:
  - name: web
    image:
      registry_type: DOCR
      repository: web
      tag: v2
    http_port: 8080
    instance_size_slug: basic-xxs
    instance_count: 1
    routes:
      - path: /
    envs:
      - key: NEXT_PUBLIC_API_BASE
        value: https://api.zkalphaflow.com
      - key: NEXT_PUBLIC_API_WS_BASE
        value: wss://api.zkalphaflow.com
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        value: pk_live_Y2xlcmsuemthbHBoYWZsb3cuY29tJA

domains:
  - domain: zkalphaflow.com
    type: PRIMARY
  - domain: www.zkalphaflow.com
    type: ALIAS
