name: zkalphaflow
region: nyc

services:
  # Next.js Frontend - Build from source
  - name: web
    github:
      repo: Nexa-Inc25/xrpcoreflowalpha
      branch: main
      deploy_on_push: true
    source_dir: apps/web
    dockerfile_path: apps/web/Dockerfile
    http_port: 3000
    instance_size_slug: basic-xxs
    instance_count: 1
    routes:
      - path: /
    envs:
      - key: NEXT_PUBLIC_API_BASE
        value: https://api.zkalphaflow.com
      - key: NEXT_PUBLIC_API_WS_BASE
        value: wss://api.zkalphaflow.com
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        value: pk_live_Y2xlcmsuemthbHBoYWZsb3cuY29tJA
      - key: NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL
        value: "/"
      - key: NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL
        value: "/"

  # FastAPI Backend - Build from source with multi-asset support
  - name: api
    github:
      repo: Nexa-Inc25/xrpcoreflowalpha
      branch: main
      deploy_on_push: true
    source_dir: /
    dockerfile_path: Dockerfile
    http_port: 8000
    instance_size_slug: basic-xs
    instance_count: 1
    routes:
      - path: /api
        preserve_path_prefix: true
    envs:
      - key: DATABASE_URL
        type: SECRET
      - key: ALCHEMY_WS_URL
        type: SECRET
      - key: ALCHEMY_API_KEY
        type: SECRET
      - key: XRPL_WSS
        value: "wss://s1.ripple.com/"
      - key: FINNHUB_API_KEY
        type: SECRET
      - key: POLYGON_API_KEY
        type: SECRET
      - key: COINGECKO_API_KEY
        type: SECRET
      - key: SOLANA_RPC_URL
        type: SECRET
      - key: SENTRY_DSN
        type: SECRET
      - key: ALERTS_SLACK_WEBHOOK
        type: SECRET
      - key: WHALE_ALERT_API_KEY
        type: SECRET
      - key: ALPHA_VANTAGE_API_KEY
        type: SECRET
      - key: REDIS_URL
        type: SECRET
      # Multi-asset correlation engine
      - key: ENABLE_EQUITY_CORRELATION
        value: "true"
      - key: ENABLE_FUTURES_CORRELATION
        value: "true"
      - key: ENABLE_FOREX_CORRELATION
        value: "true"
      - key: CORRELATION_UPDATE_INTERVAL
        value: "60"
      - key: POSTGRES_HOST
        type: SECRET
      - key: POSTGRES_PORT
        value: "25060"
      - key: POSTGRES_DB
        type: SECRET
      - key: POSTGRES_USER
        type: SECRET
      - key: POSTGRES_PASSWORD
        type: SECRET
      - key: POSTGRES_SSLMODE
        value: "require"
      - key: APP_ENV
        value: "prod"
      # CORS Configuration
      - key: CORS_ALLOW_ORIGINS
        value: "https://zkalphaflow-q3alj.ondigitalocean.app,https://zkalphaflow.com,http://localhost:3000"
      # Latency tracking and XGBoost
      - key: BINANCE_WS_URL
        value: "wss://stream.binance.com:9443/ws"
      - key: LATENCY_PING_INTERVAL
        value: "5"
      - key: XGBOOST_RETRAIN_INTERVAL
        value: "86400"
      # Educator/course webhook
      - key: SLACK_EDUCATOR_WEBHOOK_URL
        type: SECRET
      # Slack bot token for interactive features
      - key: SLACK_BOT_TOKEN
        type: SECRET
      # Latency alert thresholds
      - key: MIN_LATENCY_ANOMALY_SCORE
        value: "75"
      - key: HFT_LATENCY_THRESHOLD
        value: "50"
      # Wallet analysis APIs
      - key: ETHERSCAN_API_KEY
        type: SECRET
      - key: DUNE_API_KEY
        type: SECRET
      # Clerk Authentication
      - key: CLERK_SECRET_KEY
        type: SECRET
      # Slack Education Integration
      - key: SLACK_COURSE_WEBHOOK_URL
        type: SECRET
      - key: ENABLE_SLACK_COURSES
        value: "true"

workers:
  # Background worker for Redis events and Slack notifications
  - name: worker
    github:
      repo: Nexa-Inc25/xrpcoreflowalpha
      branch: main
      deploy_on_push: true
    source_dir: /
    dockerfile_path: Dockerfile
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: DATABASE_URL
        type: SECRET
      - key: ALCHEMY_WS_URL
        type: SECRET
      - key: ALERTS_SLACK_WEBHOOK
        type: SECRET
      - key: REDIS_URL
        type: SECRET

domains:
  - domain: zkalphaflow.com
    type: PRIMARY
  - domain: www.zkalphaflow.com
    type: ALIAS
